# Generated by Django 4.1 on 2022-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, default='+255', max_length=13, null=True)),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('to_dimoso_email', models.EmailField(blank=True, default='juniordimoso8@gmail.com', max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'ContactMe',
            },
        ),
    ]
