# Generated by Django 4.1 on 2022-10-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_contactme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='to_dimoso_email',
        ),
    ]
