# Generated by Django 4.1.3 on 2023-07-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_products_similarimage1_products_similarimage2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SimilarImage10',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_10/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage11',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_11/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage12',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_12/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage13',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_13/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage14',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_14/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage15',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_15/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage16',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_16/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage17',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_17/'),
        ),
        migrations.AddField(
            model_name='products',
            name='SimilarImage18',
            field=models.ImageField(blank=True, null=True, upload_to='SimilarPartsImages_18/'),
        ),
    ]
