# Generated by Django 4.1.3 on 2023-07-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_products_similarimage10_products_similarimage11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
    ]
